#!/system/bin/sh

RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
RESET="\033[0m"

printf "${GREEN}-#-#-#-#-#-#-#-#-${RESET}\n"
printf "${GREEN}UnieDroid 0.1.0 Alpha 1${RESET}\n"
printf "${YELLOW}-#-#-#-#-#-#-#-#-${RESET}\n"
